export const SUPABASE_URL = 'https://mfqydzcdynwbovaxyede.supabase.co';
export const SUPABASE_KEY =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mcXlkemNkeW53Ym92YXh5ZWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTAwNzczNzAsImV4cCI6MjAyNTY1MzM3MH0.SrYkCAcBbzS4V9jpxg_6l04OYB6jkSf3P5rtZQY1QtE';
